import { Product } from '../types';

export interface SeedProduct extends Omit<Product, 'id'> {}

const now = Date.now();

export const SEED_PRODUCTS: SeedProduct[] = [
  // ── ELECTRONICS ──
  {
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and ultra-comfortable memory foam ear cushions. Features Bluetooth 5.3 and multipoint connection.',
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/headphones/400/400',
    currentPrice: 149.99,
    originalPrice: 249.99,
    currency: 'USD',
    createdAt: now - 1 * 86400000,
  },
  {
    name: 'Smart Watch Pro Series',
    description: 'Advanced fitness tracking smartwatch with heart rate monitor, GPS, sleep tracking, and a vibrant AMOLED display. Water-resistant to 50 meters.',
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/smartwatch/400/400',
    currentPrice: 199.99,
    originalPrice: 299.99,
    currency: 'USD',
    createdAt: now - 2 * 86400000,
  },
  {
    name: 'Bluetooth Portable Speaker',
    description: 'Rugged waterproof speaker with 360-degree sound, 20-hour playtime, and built-in microphone. Perfect for outdoor adventures.',
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/speaker/400/400',
    currentPrice: 59.99,
    originalPrice: 79.99,
    currency: 'USD',
    createdAt: now - 3 * 86400000,
  },
  {
    name: 'USB-C Hub Adapter 7-in-1',
    description: 'Compact multiport adapter with HDMI 4K, USB 3.0, SD card reader, and 100W Power Delivery pass-through charging.',
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/usbhub/400/400',
    currentPrice: 34.99,
    originalPrice: 49.99,
    currency: 'USD',
    createdAt: now - 4 * 86400000,
  },
  {
    name: 'Mechanical Keyboard RGB',
    description: 'Full-size mechanical keyboard with hot-swappable switches, per-key RGB lighting, and aircraft-grade aluminum frame.',
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/keyboard/400/400',
    currentPrice: 89.99,
    originalPrice: 129.99,
    currency: 'USD',
    createdAt: now - 5 * 86400000,
  },
  {
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charger compatible with all Qi devices. Supports 15W fast charge with intelligent temperature control.',
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/charger/400/400',
    currentPrice: 24.99,
    originalPrice: 39.99,
    currency: 'USD',
    createdAt: now - 6 * 86400000,
  },
  {
    name: '4K Webcam with Ring Light',
    description: 'Ultra HD webcam with built-in adjustable ring light, auto-focus, and noise-cancelling dual microphones for crystal-clear video calls.',
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/webcam/400/400',
    currentPrice: 69.99,
    originalPrice: 99.99,
    currency: 'USD',
    createdAt: now - 7 * 86400000,
  },
  {
    name: 'Portable Power Bank 20000mAh',
    description: 'High-capacity power bank with dual USB-C and USB-A outputs. Supports fast charging for phones, tablets, and laptops.',
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/powerbank/400/400',
    currentPrice: 39.99,
    originalPrice: 54.99,
    currency: 'USD',
    createdAt: now - 8 * 86400000,
  },

  // ── FASHION ──
  {
    name: 'Classic Leather Jacket',
    description: 'Timeless genuine leather jacket with a tailored fit, quilted lining, and silver-toned zippers. A wardrobe essential for any season.',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/jacket/400/400',
    currentPrice: 189.99,
    originalPrice: 279.99,
    currency: 'USD',
    createdAt: now - 9 * 86400000,
  },
  {
    name: 'Slim Fit Chino Pants',
    description: 'Stretch cotton chinos with a modern slim fit. Features a mid-rise waist and tapered leg. Available in multiple colors.',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/chinos/400/400',
    currentPrice: 49.99,
    originalPrice: 69.99,
    currency: 'USD',
    createdAt: now - 10 * 86400000,
  },
  {
    name: 'Cashmere Blend Sweater',
    description: 'Luxuriously soft cashmere-blend crewneck sweater. Perfect for layering with a relaxed fit and ribbed cuffs.',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/sweater/400/400',
    currentPrice: 79.99,
    originalPrice: 119.99,
    currency: 'USD',
    createdAt: now - 11 * 86400000,
  },
  {
    name: 'Running Sneakers Ultraboost',
    description: 'Lightweight performance sneakers with responsive cushioning, breathable knit upper, and superior traction outsole.',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/sneakers/400/400',
    currentPrice: 129.99,
    originalPrice: 169.99,
    currency: 'USD',
    createdAt: now - 12 * 86400000,
  },
  {
    name: 'Aviator Sunglasses',
    description: 'Classic gold-frame aviator sunglasses with polarized UV400 lenses. Lightweight and timeless design.',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/sunglasses/400/400',
    currentPrice: 34.99,
    originalPrice: 59.99,
    currency: 'USD',
    createdAt: now - 13 * 86400000,
  },
  {
    name: 'Canvas Backpack',
    description: 'Vintage-style canvas backpack with padded laptop compartment, multiple pockets, and genuine leather trims.',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/backpack/400/400',
    currentPrice: 54.99,
    originalPrice: 74.99,
    currency: 'USD',
    createdAt: now - 14 * 86400000,
  },
  {
    name: 'Silk Tie Set',
    description: 'Set of two premium silk ties in classic patterns. Each tie features a self-tipping lining and a 7-fold construction.',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/ties/400/400',
    currentPrice: 29.99,
    originalPrice: 44.99,
    currency: 'USD',
    createdAt: now - 15 * 86400000,
  },
  {
    name: 'Denim Jacket',
    description: 'Classic denim jacket with button-front closure, chest pockets, and adjustable waist tabs. A versatile layering piece.',
    category: 'Fashion',
    imageUrl: 'https://picsum.photos/seed/denim/400/400',
    currentPrice: 69.99,
    originalPrice: 89.99,
    currency: 'USD',
    createdAt: now - 16 * 86400000,
  },

  // ── HOME ──
  {
    name: 'Scented Soy Candle Set',
    description: 'Set of 3 hand-poured soy candles in lavender, vanilla, and eucalyptus. Burns for 45+ hours each in elegant glass jars.',
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/candles/400/400',
    currentPrice: 28.99,
    originalPrice: 39.99,
    currency: 'USD',
    createdAt: now - 17 * 86400000,
  },
  {
    name: 'Memory Foam Throw Pillow',
    description: 'Ultra-soft memory foam pillow with removable bamboo cover. Provides excellent neck and lumbar support.',
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/pillow/400/400',
    currentPrice: 24.99,
    originalPrice: 34.99,
    currency: 'USD',
    createdAt: now - 18 * 86400000,
  },
  {
    name: 'Smart LED Desk Lamp',
    description: 'Adjustable LED desk lamp with touch control, 5 color modes, and 7 brightness levels. USB charging port built in.',
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/lamp/400/400',
    currentPrice: 39.99,
    originalPrice: 59.99,
    currency: 'USD',
    createdAt: now - 19 * 86400000,
  },
  {
    name: 'Ceramic Plant Pot Set',
    description: 'Set of 3 minimalist ceramic plant pots with drainage holes and bamboo trays. Perfect for succulents and small plants.',
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/plantpots/400/400',
    currentPrice: 32.99,
    originalPrice: 44.99,
    currency: 'USD',
    createdAt: now - 20 * 86400000,
  },
  {
    name: 'Microfiber Cleaning Cloth Set',
    description: 'Pack of 12 premium microfiber cleaning cloths. Lint-free, absorbent, and reusable. Ideal for glass, kitchen, and electronics.',
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/cleaning/400/400',
    currentPrice: 14.99,
    originalPrice: 19.99,
    currency: 'USD',
    createdAt: now - 21 * 86400000,
  },
  {
    name: 'Stainless Steel Water Bottle',
    description: 'Double-wall vacuum insulated bottle keeps drinks cold 24h or hot 12h. BPA-free, leak-proof, 750ml capacity.',
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/bottle/400/400',
    currentPrice: 22.99,
    originalPrice: 34.99,
    currency: 'USD',
    createdAt: now - 22 * 86400000,
  },
  {
    name: 'Bamboo Cutting Board',
    description: 'Large organic bamboo cutting board with juice groove and built-in handles. Naturally antimicrobial and knife-friendly.',
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/cuttingboard/400/400',
    currentPrice: 26.99,
    originalPrice: 36.99,
    currency: 'USD',
    createdAt: now - 23 * 86400000,
  },
  {
    name: 'Weighted Blanket 15lbs',
    description: 'Premium cotton weighted blanket with glass bead filling. Promotes deeper sleep and reduced anxiety. Machine washable cover.',
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/blanket/400/400',
    currentPrice: 59.99,
    originalPrice: 89.99,
    currency: 'USD',
    createdAt: now - 24 * 86400000,
  },

  // ── SPORTS ──
  {
    name: 'Yoga Mat Premium',
    description: 'Extra-thick 6mm eco-friendly TPE yoga mat with alignment lines. Non-slip surface, lightweight, and includes carrying strap.',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/seed/yogamat/400/400',
    currentPrice: 39.99,
    originalPrice: 54.99,
    currency: 'USD',
    createdAt: now - 25 * 86400000,
  },
  {
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells from 5lbs to 52.5lbs. Quick-change weight system with ergonomic grip handle.',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/seed/dumbbells/400/400',
    currentPrice: 199.99,
    originalPrice: 299.99,
    currency: 'USD',
    createdAt: now - 26 * 86400000,
  },
  {
    name: 'Resistance Bands Set',
    description: 'Set of 5 resistance bands with varying tension levels. Includes door anchor, ankle straps, and carrying bag.',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/seed/bands/400/400',
    currentPrice: 24.99,
    originalPrice: 34.99,
    currency: 'USD',
    createdAt: now - 27 * 86400000,
  },
  {
    name: 'Insulated Water Bottle 1L',
    description: 'Triple-wall vacuum insulated stainless steel bottle. Keeps water ice-cold during intense workouts. Leak-proof sport cap.',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/seed/sportsbottle/400/400',
    currentPrice: 19.99,
    originalPrice: 29.99,
    currency: 'USD',
    createdAt: now - 28 * 86400000,
  },
  {
    name: 'Jump Rope Speed',
    description: 'Ball-bearing speed jump rope with adjustable cable and foam handles. Ideal for boxing training and HIIT workouts.',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/seed/jumprope/400/400',
    currentPrice: 14.99,
    originalPrice: 22.99,
    currency: 'USD',
    createdAt: now - 29 * 86400000,
  },
  {
    name: 'Foam Roller Muscle Recovery',
    description: 'High-density foam roller for muscle recovery and myofascial release. Features a hollow core for deep tissue massage.',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/seed/foamroller/400/400',
    currentPrice: 29.99,
    originalPrice: 44.99,
    currency: 'USD',
    createdAt: now - 30 * 86400000,
  },
  {
    name: 'Cycling Gloves Padded',
    description: 'Breathable mesh cycling gloves with gel padding, silicone grip, and touchscreen-compatible fingertips.',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/seed/gloves/400/400',
    currentPrice: 19.99,
    originalPrice: 27.99,
    currency: 'USD',
    createdAt: now - 31 * 86400000,
  },
  {
    name: 'Swimming Goggles Anti-Fog',
    description: 'Competition-grade swimming goggles with anti-fog coating, UV protection, and adjustable silicone strap. 4 colors included.',
    category: 'Sports',
    imageUrl: 'https://picsum.photos/seed/goggles/400/400',
    currentPrice: 16.99,
    originalPrice: 24.99,
    currency: 'USD',
    createdAt: now - 32 * 86400000,
  },

  // ── BEAUTY ──
  {
    name: 'Vitamin C Serum',
    description: 'Concentrated 20% Vitamin C serum with hyaluronic acid and Vitamin E. Brightens skin, reduces dark spots, and boosts collagen.',
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/serum/400/400',
    currentPrice: 34.99,
    originalPrice: 49.99,
    currency: 'USD',
    createdAt: now - 33 * 86400000,
  },
  {
    name: 'Retinol Moisturizer Cream',
    description: 'Anti-aging night cream with encapsulated retinol, peptides, and ceramides. Reduces fine lines and improves skin texture.',
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/moisturizer/400/400',
    currentPrice: 42.99,
    originalPrice: 64.99,
    currency: 'USD',
    createdAt: now - 34 * 86400000,
  },
  {
    name: 'Hair Dryer Ionic Pro',
    description: 'Professional ionic hair dryer with 3 heat settings, 2 speed settings, and concentrator nozzle. Reduces frizz and drying time.',
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/hairdryer/400/400',
    currentPrice: 54.99,
    originalPrice: 79.99,
    currency: 'USD',
    createdAt: now - 35 * 86400000,
  },
  {
    name: 'Makeup Brush Set 12-Piece',
    description: 'Complete set of 12 premium synthetic makeup brushes with travel case. Includes face, eye, and complexion brushes.',
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/brushes/400/400',
    currentPrice: 29.99,
    originalPrice: 44.99,
    currency: 'USD',
    createdAt: now - 36 * 86400000,
  },
  {
    name: 'SPF 50 Sunscreen Lotion',
    description: 'Lightweight reef-safe sunscreen with broad-spectrum SPF 50. Water-resistant for 80 minutes. Non-greasy formula.',
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/sunscreen/400/400',
    currentPrice: 18.99,
    originalPrice: 26.99,
    currency: 'USD',
    createdAt: now - 37 * 86400000,
  },
  {
    name: 'Nail Polish Gel Set',
    description: 'Set of 6 long-lasting gel nail polish colors. UV/LED cured, chip-resistant, and salon-quality finish.',
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/nailpolish/400/400',
    currentPrice: 22.99,
    originalPrice: 34.99,
    currency: 'USD',
    createdAt: now - 38 * 86400000,
  },
  {
    name: 'Face Steamer Spa',
    description: 'Professional nano-ionic facial steamer with adjustable steam control. Opens pores and deep cleanses for spa-like results at home.',
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/steamer/400/400',
    currentPrice: 44.99,
    originalPrice: 64.99,
    currency: 'USD',
    createdAt: now - 39 * 86400000,
  },
  {
    name: 'Essential Oils Starter Kit',
    description: 'Set of 8 pure essential oils: lavender, peppermint, tea tree, eucalyptus, lemon, orange, rosemary, and frankincense.',
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/oils/400/400',
    currentPrice: 26.99,
    originalPrice: 38.99,
    currency: 'USD',
    createdAt: now - 40 * 86400000,
  },

  // ── BOOKS ──
  {
    name: 'The Art of Clean Code',
    description: 'A practical guide to writing readable, maintainable, and efficient code. Covers design patterns, refactoring, and best practices.',
    category: 'Books',
    imageUrl: 'https://picsum.photos/seed/cleancode/400/400',
    currentPrice: 29.99,
    originalPrice: 44.99,
    currency: 'USD',
    createdAt: now - 41 * 86400000,
  },
  {
    name: 'Data Structures & Algorithms',
    description: 'Comprehensive guide to data structures and algorithms with real-world examples in JavaScript and Python.',
    category: 'Books',
    imageUrl: 'https://picsum.photos/seed/datastructures/400/400',
    currentPrice: 39.99,
    originalPrice: 54.99,
    currency: 'USD',
    createdAt: now - 42 * 86400000,
  },
  {
    name: 'The Midnight Library',
    description: 'A thought-provoking novel about a woman who gets to explore alternate versions of her life in a magical library between life and death.',
    category: 'Books',
    imageUrl: 'https://picsum.photos/seed/midnight/400/400',
    currentPrice: 14.99,
    originalPrice: 22.99,
    currency: 'USD',
    createdAt: now - 43 * 86400000,
  },
  {
    name: 'Atomic Habits',
    description: 'An easy and proven way to build good habits and break bad ones. Discover the power of small changes for remarkable results.',
    category: 'Books',
    imageUrl: 'https://picsum.photos/seed/habits/400/400',
    currentPrice: 16.99,
    originalPrice: 24.99,
    currency: 'USD',
    createdAt: now - 44 * 86400000,
  },
  {
    name: 'The Great Gatsby',
    description: 'F. Scott Fitzgerald\'s masterpiece about the decadence of the Jazz Age, the American Dream, and love lost and found.',
    category: 'Books',
    imageUrl: 'https://picsum.photos/seed/gatsby/400/400',
    currentPrice: 11.99,
    originalPrice: 18.99,
    currency: 'USD',
    createdAt: now - 45 * 86400000,
  },
  {
    name: 'JavaScript: The Good Parts',
    description: 'A deep dive into the best features of JavaScript. Learn how to write robust, efficient code by focusing on what works.',
    category: 'Books',
    imageUrl: 'https://picsum.photos/seed/javascript/400/400',
    currentPrice: 24.99,
    originalPrice: 34.99,
    currency: 'USD',
    createdAt: now - 46 * 86400000,
  },
  {
    name: 'Sapiens: A Brief History',
    description: 'A groundbreaking narrative of humanity\'s creation and evolution that explores how we came to dominate the planet.',
    category: 'Books',
    imageUrl: 'https://picsum.photos/seed/sapiens/400/400',
    currentPrice: 18.99,
    originalPrice: 28.99,
    currency: 'USD',
    createdAt: now - 47 * 86400000,
  },
  {
    name: 'The Alchemist',
    description: 'A magical fable about following your dreams. Paulo Coelho\'s timeless story of a shepherd boy\'s journey to find treasure.',
    category: 'Books',
    imageUrl: 'https://picsum.photos/seed/alchemist/400/400',
    currentPrice: 12.99,
    originalPrice: 19.99,
    currency: 'USD',
    createdAt: now - 48 * 86400000,
  },
];
